### PR TITLE
Update to reference version 1.2

### PR DESCRIPTION
**Pull request by mowasfi7**
The old v1.0 was referenced

### CODE REVIEW

**Comment by jayshao** [comment]
How do people feel about just removing the PDF? I think in practice the Markdown will be easier to both maintain and collab-edit

**Comment by jasleenk-viooh** [comment]
+1

**Comment by mowasfi7** [comment]
Works for me. Can we maybe merge this as the old version is referenced by media outlets e.g. https://www.mediapost.com/publications/article/358507/digital-ooh-suppliers-standardize-ad-formats-venu.html and doesn't cover all participants?

And work on shifting to MD later?

**Comment by jayshao** [comment]
I have a PR open for shifting to MD, if I can get some eyes on it and merge that in - mostly I think we're going to want to renumber to align with semantic versioning - and don't want to push another doc with 1.2 - will poke folks in Slack

**Comment by mowasfi7** [comment]
Addressed in https://github.com/openooh/venue-taxonomy/pull/38

**Pull request closed without merging**
