### PR TITLE
Removing company blurbs from specs MD

### PR DESCRIPTION
**Pull request by mowasfi7**
Contributors are already called out on the read me page. Removing them from here so we don't have to maintain them in 2 locations and to keep this for specs only. Let me know what you think

### CODE REVIEW

**Comment by jayshao** [comment]
You know - I was looking at that block too and was wondering if we should trim it as a remnant of this having been a standalone document.

I suspect the people's names has value - but the company blurbs is overkill. E.g. I think the way TechLab let's you know who a given spec's contributors is is valuable - and maybe a reasonable middle ground?

**Comment by mowasfi7** [comment]
@jayshao fair enough! Agreed. I reintroduced the individual contributors based on activity so far. We can add more individual names next to the company names as we go.

**Comment by mmercuri-broadsign** [comment]
Good with it? any last opinions?

**Comment by christiancollins11** [comment]
+1

**Review by jayshao — APPROVED** [review]
lgtm

**Pull request merged**
