### PR TITLE
Lucit fix to college grandchildren ids

### PR DESCRIPTION
**Pull request by ericlucit**
@ericlucit
Fixed the enumeration_ids for the grandchildren of Colleges and Universities

The Colleges and Universities category is ID `602` but its grandchildren were listed as `60101`,`60102`,`60103`

This fixes the ids to have the correct `602` prefix

Also, added a generic `.gitignore` - Which will be needed for potential future tools, etc.   If you don't want this yet, it can be removed

### CODE REVIEW

**Comment by jayshao** [comment]
I think this makes sense. @ericlucit can you merge this into the `working-1.1` branch instead of straight into `main` ?

It does make me wonder... does this pose compatibility problems for re-parenting? While we could in principle deprecate and replace... I wonder if we would be in a better spot if we did not embed the hierarchy in the numbers (e.g. just sequential or the like) Esp. since it's kind of "hierarchical, except within a level where it's sequential...

**Review by jayshao — APPROVED** [review]
lgtm with the caveat i'd like to merge working changes into `working-1.1` to keep the version for public review stable until we end the review period

**Comment by ericlucit** [comment]
> lgtm with the caveat i'd like to merge working changes into `working-1.1` to keep the version for public review stable until we end the review period

I changed the base to `working-1.1`

**Comment by ericlucit** [comment]
> I think this makes sense. @ericlucit can you merge this into the `working-1.1` branch instead of straight into `main` ?
> 
> It does make me wonder... does this pose compatibility problems for re-parenting? While we could in principle deprecate and replace... I wonder if we would be in a better spot if we did not embed the hierarchy in the numbers (e.g. just sequential or the like) Esp. since it's kind of "hierarchical, except within a level where it's sequential...

And further to that, we do have a child limitation of 99 children per parent with the current setup..   Sounds like a lot and maybe that is OK, but, it is a technical limit based on this numbering scheme

**Comment by ericlucit** [comment]
Note, I am unable to merge as I do not have write access

**Pull request merged**
